/* Generated by Together */

#include "stdafx.h"
#include "IPropertyHost.h"
#include "EPropWndEdit.h"
#include "EPropertyString.h"

EPropertyString::EPropertyString( IPropertyHost* pHost , const CString& sName , CString* pProperty , bool bEnabled ) : EIconTextButtonProperty( pHost , sName , pProperty , bEnabled )
{
}

EPropertyString::~EPropertyString()
{
}


bool EPropertyString::OnPropApply()
{
	ASSERT( m_bSelected == true );
	ASSERT( m_pEdit     != NULL );
	ASSERT( IsEnabled() == true );

	CString s;
	m_pEdit->GetWindowText(s);

	bool bPropertyChanged = false;

	if( ((CString*)m_pProperty)->Compare(s) != 0 )
	{
		if( m_pHost->PropertyChanging(m_pProperty,&s) )
		{
			*((CString*)m_pProperty) = s;
			bPropertyChanged = true;
		}
	}

	return bPropertyChanged;
}

CString EPropertyString::GetTextValue()
{
	CString s;

	if( m_pProperty != NULL )
	{
		s = *((CString*)m_pProperty);
	}

	return s;
}

bool EPropertyString::HasEdit()
{
	return true;
}


CString EPropertyCharString::GetTextValue()
{
	const char* s = (const char*)m_pProperty;

	CString rr;

	if( m_nStringLength>0 )
	{
		for( int i=0 ; i<m_nStringLength ; i++ )
		{
			if( s[i]==0 )
			{
				break;
			}

			rr += s[i];
		}
	}
	else
	{
		CString ss(s);
		rr = ss;
	}

	return rr;
}
