/* Generated by Together */

#ifndef EPROPERTYSTRING_H
#define EPROPERTYSTRING_H

#include "EIconTextButtonProperty.h"

class IPropertyHost;

class GUILIBDLLEXPORT EPropertyString : public EIconTextButtonProperty
{

public:

	//
	// construction/destruction
	//
    EPropertyString( IPropertyHost* pHost , const CString& sName , CString* pProperty , bool bEnabled = true );
	~EPropertyString();

	//
	// EIconTextButtonProperty
	//
	virtual CString GetTextValue();
	virtual bool OnPropApply();

	//
	// this
	//
	virtual bool HasEdit();


};

class EPropertyCharString : public EIconTextButtonProperty
{
	int m_nStringLength;

public:

//always read-only, untill apply is implemented
//	EPropertyCharString( IPropertyHost* pHost , const CString& sName , char* pProperty , int nLength=0 , bool bEnabled=false ) : EIconTextButtonProperty( pHost , sName , pProperty , bEnabled )
	EPropertyCharString( IPropertyHost* pHost , const CString& sName , char* pProperty , int nLength=0 ) : EIconTextButtonProperty( pHost , sName , pProperty , false )
	{
		m_nStringLength = nLength;
	}

	virtual CString GetTextValue();

};

#endif //EPROPERTYSTRING_H